- name: Build for x86_64
  shell: bash
  env:
    DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
    DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    RELEASE: ${{ env.RELEASE }}
  run: ./.github/scripts/build.sh x86_64

- name: Build for armv6l
  shell: bash
  env:
    DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
    DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    RELEASE: ${{ env.RELEASE }}
  run: ./.github/scripts/build.sh armv6l

- name: Build for aarch64
  shell: bash
  env:
    DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
    DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    RELEASE: ${{ env.RELEASE }}
  run: ./.github/scripts/build.sh aarch64
